version: "3.8"

name: ncfs-complex

networks:
    ncfs-net:
        name: ncfs-net

services:
    ncfs:
        image: barbarbar338/ncfs:buildx-latest
        container_name: ncfs
        restart: unless-stopped
        ports:
            - 4040:4040
        volumes:
            - ./config.json:/app/config.json
        networks:
            - ncfs-net
