version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    restart: unless-stopped
    environment:
      EULA: "true"
      TYPE: PAPER
    ports:
      - 25565:25565/tcp
    volumes:
      - ./mc-data:/data
    networks:
      - ngrok-net

  ncfs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ncfs
    depends_on:
      - mc
    restart: unless-stopped
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/root/.config/ngrok/ngrok.yml
      - ./config.json:/app/config.json
    networks:
      - ngrok-net
    environment:
      - DOCKER_MC_NETWORK=mc

networks:
  ngrok-net:
    name: ngrok-net
